# https://github.com/actions/deploy-pages#usage
name: Deploy to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:  
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
          terraform_version: 1.13.4 
      # Build API Layer and get latest results
      - name: Build API Layer
        run: |
          cd scripts
          ./build_layer.sh prod
          aws dynamodb query --table-name tobiagg-prod --key-condition-expression 'pk=:pk1 AND sk=:sk' --expression-attribute-values '{":pk1":{"S":"miner" }, ":sk":{"S":"total"}}' > ../frontend/miner.json
          aws dynamodb query --table-name tobiagg-prod --key-condition-expression 'pk=:pk1 AND sk=:sk' --expression-attribute-values '{":pk1":{"S":"millionaire" }, ":sk":{"S":"total"}}' > ../frontend/millionaire.json
          aws dynamodb query --table-name tobiagg-prod --key-condition-expression 'pk=:pk1 AND sk=:sk' --expression-attribute-values '{":pk1":{"S":"carer" }, ":sk":{"S":"total"}}' > ../frontend/carer.json
          aws dynamodb query --table-name tobiagg-prod --key-condition-expression 'pk=:pk1 AND sk=:sk' --expression-attribute-values '{":pk1":{"S":"careleaver" }, ":sk":{"S":"total"}}' > ../frontend/careleaver.json
          aws dynamodb query --table-name tobiagg-prod --key-condition-expression 'pk=:pk1 AND sk=:sk' --expression-attribute-values '{":pk1":{"S":"farmer" }, ":sk":{"S":"total"}}' > ../frontend/farmer.json
          aws dynamodb query --table-name tobiagg-prod --key-condition-expression 'pk=:pk1 AND sk=:sk' --expression-attribute-values '{":pk1":{"S":"student" }, ":sk":{"S":"total"}}' > ../frontend/student.json
          aws dynamodb query --table-name tobiagg-prod --key-condition-expression 'pk=:pk1 AND sk=:sk' --expression-attribute-values '{":pk1":{"S":"refugee" }, ":sk":{"S":"total"}}' > ../frontend/refugee.json
          aws dynamodb query --table-name tobiagg-prod --key-condition-expression 'pk=:pk1 AND sk=:sk' --expression-attribute-values '{":pk1":{"S":"disabled" }, ":sk":{"S":"total"}}' > ../frontend/disabled.json
      # Run terraform deployment
      - name: Terraform Deployment
        run: |
          cd terraform
          terraform init
          terraform workspace select -or-create prod
          terraform apply -auto-approve
          terraform output -json > ../frontend/config.json

      # Pick your own package manager and build script
      - run: cd frontend; npm install
      - run: cd frontend; npx nuxt generate --preset github_pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./frontend/dist/
  # Deployment job
  deploy:
    # Add a dependency to the build job
    needs: build
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    # Deploy to the github_pages environment
    environment:
      name: github_pages
      url: ${{ steps.deployment.outputs.page_url }}
    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4